### PR TITLE
CNI: update antrea to 1.8.0

### PR DESCRIPTION
**Pull request by dougsland**
Signed-off-by: Douglas Schilling Landgraf <dougsland@redhat.com>

### CODE REVIEW

**Comment by dougsland** [comment]
still seeing: 

```
    winw1: Exception calling "Read" with "3" argument(s): "Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection."
    winw1: At line:100 char:11
    winw1: +       if ($fs.Read($bytes, 0, $fs.Length) -gt 0) {
    winw1: +           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    winw1:     + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    winw1:     + FullyQualifiedErrorId : ArgumentException
    winw1:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
    winw1:                                  Dload  Upload   Total   Spent    Left  Speed
100  9422  100  9422    0     0  44610      0 --:--:-- --:--:-- --:--:-- 45081
    winw1: DEBUG:   58+      if ( >>>> $theURL -eq
```

I will continue digging.

**Comment by jayunit100** [comment]
/lgtm
/approve

Let's merge anyway as it's the latest thanks dougums!!!

**Comment by knabben** [comment]
/lgtm

Let's upgrade the change we need seems to be on 1.8

**Comment by knabben** [comment]
```   
winw1: C:\tmp\vagrant-shell.ps1 : Exception calling "FromBase64String" with "1" argument(s): "Value cannot be null.
    winw1: Parameter name: s"
```

seems to be raised from https://github.com/kubernetes-sigs/sig-windows-dev-tools/blob/f5a1223836ab06094dba81b008e37312738487ad/sync/windows/1-antrea.ps1#L62

maybe the query annotation below is not being used anymore.

**Comment by dougsland** [comment]
> ```
> winw1: C:\tmp\vagrant-shell.ps1 : Exception calling "FromBase64String" with "1" argument(s): "Value cannot be null.
>     winw1: Parameter name: s"
> ```
> 
> seems to be raised from
> 
> https://github.com/kubernetes-sigs/sig-windows-dev-tools/blob/f5a1223836ab06094dba81b008e37312738487ad/sync/windows/1-antrea.ps1#L62
> 
> maybe the query annotation below is not being used anymore.

Thanks Amim! I am debugging my env and I can't see `C:/k/antrea/etc/kube-proxy.conf` which will not make https://github.com/kubernetes-sigs/sig-windows-dev-tools/blob/master/sync/windows/1-antrea.ps1#L59-L62  work.

@knabben should we be shipping a default config in the project? I can't find `kube-proxy.conf` file in antrea or sig-windows-dev-tools projects.
 
```
C:\sync> ls c:/k/antrea/etc


    Directory: C:\k\antrea\etc


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----        8/28/2022  10:33 PM           9397 antrea-agent.conf
```

**Comment by dougsland** [comment]
> > ```
> > winw1: C:\tmp\vagrant-shell.ps1 : Exception calling "FromBase64String" with "1" argument(s): "Value cannot be null.
> >     winw1: Parameter name: s"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > seems to be raised from
> > https://github.com/kubernetes-sigs/sig-windows-dev-tools/blob/f5a1223836ab06094dba81b008e37312738487ad/sync/windows/1-antrea.ps1#L62
> > 
> > maybe the query annotation below is not being used anymore.
> 
> Thanks Amim! I am debugging my env and I can't see `C:/k/antrea/etc/kube-proxy.conf` which will not make https://github.com/kubernetes-sigs/sig-windows-dev-tools/blob/master/sync/windows/1-antrea.ps1#L59-L62 work.
> 
> @knabben should we be shipping a default config in the project? I can't find `kube-proxy.conf` file in antrea or sig-windows-dev-tools projects.
> 
> ```
> C:\sync> ls c:/k/antrea/etc
> 
> 
>     Directory: C:\k\antrea\etc
> 
> 
> Mode                LastWriteTime         Length Name
> ----                -------------         ------ ----
> -a----        8/28/2022  10:33 PM           9397 antrea-agent.conf
> ```

answering my own question after speaking with `Antoni Bas`, it's created by `kubectl config` in the script.

**Comment by dougsland** [comment]
The current issue in the antrea deploy is not related to this one, unhold for merge.
/unhold

**Pull request merged**
