### PR TITLE
build: add .lock for cni and joined

### PR DESCRIPTION
**Pull request by dougsland**
These files are build semaphores only and can be hidden
and ignored by git.

Signed-off-by: Douglas Schilling Landgraf <dlandgra@redhat.com>

### CODE REVIEW

**Review by aravindhp — COMMENTED** [review]
Thanks for doing this, @dougsland 

/lgtm

**Comment by dougsland** [comment]
Worked for me. Also removed 'up' file as nothing is using it as I can see.

**Review by aravindhp — COMMENTED** [review]
/lgtm

**Pull request merged**
