### PR TITLE
OWNERS file fixes + updates

### PR DESCRIPTION
**Pull request by marosset**

### CODE REVIEW

**Comment by marosset** [comment]
Hmmm @sladyn98 should be a member of the k-sigs org. Here is the PR with updates https://github.com/kubernetes/org/commit/b1083b10f1fbd9d34f83f7fb22a85193b89ac9a9

**Comment by marosset** [comment]
I asked in slack for someone to take a look.

**Comment by marosset** [comment]
https://kubernetes.slack.com/archives/C01672LSZL0/p1626202783115300

**Comment by marosset** [comment]
@sladyn98 can you check to see if you have an outstanding invite to join the kubernetes-sigs org and accept it if you have it?

**Comment by jayunit100** [comment]
mark feel free to merge this any time when your ready 
... @sladyn98 can you confirm wether  you are  going to be actively contributing to the project going forward ?

**Comment by sladyn98** [comment]
@jayunit100 Yes I will be actively contributing to it, I am just setting up some stuff after which I should be back

**Comment by sladyn98** [comment]
@marosset Looks like the invitation has expired, can I get another invite

**Comment by jayunit100** [comment]
+1 ok - sounds like we should keep slaydyn in owners since hes planning on contributing going forward , can we merge this and do the kubernetes-sigs part in another thread ?

**Comment by marosset** [comment]
@jayunit100 I need to bot to remove the do-not-merge\invalid-owners-file before I can merge this.

@sladyn98 can you respond to the thread in slack I linked above to ask for another invite?
I don't have permissions to do this.

Thanks all!

**Comment by jayunit100** [comment]
ahhhh ok

**Comment by jayunit100** [comment]
im happy to both endorse slaydyn for kubernetes-sigs as well as to merge him into OWNERS.md as well...  

to keep velocity up on this repo,  should we do that in this PR or a separate one?

**Comment by marosset** [comment]
> im happy to both endorse slaydyn for kubernetes-sigs as well as to merge him into OWNERS.md as well...
> 
> to keep velocity up on this repo, should we do that in this PR or a separate one?

Sounds good. We can get slayden re-added after this gets resolved.

**Pull request merged**
