### PR TITLE
v1.21 version fix

### PR DESCRIPTION
**Pull request by jayunit100**

### CODE REVIEW

**Review by luthermonson — APPROVED** [review]

**Comment by jayunit100** [comment]
just finished testing, worked for me ... 

defaults to the right 1.21.2 version which has the fix for https://github.com/kubernetes/kubernetes/issues/101500 


```
commit 286709307da5adb62e78d989b7ed846355d5c88e (HEAD, tag: v1.21.2-rc.0)
Author: Anago GCB <nobody@k8s.io>
Date:   Wed May 12 14:11:29 2021 +0000

    Release commit for Kubernetes v1.21.2-rc.0
```

**Comment by jayunit100** [comment]
```
➜  sig-windows-dev-tools git:(6e40996) ✗ vagrant winrm winw1 --shell=powershell --command="Get-Service *kube* "

Status   Name               DisplayName
------   ----               -----------
Running  kubelet            kubelet
Running  kube-proxy         kube-proxy


➜  sig-windows-dev-tools git:(6e40996) ✗ vagrant winrm winw1 --shell=powershell --command="Get-Service *Ant* "

Status   Name               DisplayName
------   ----               -----------
Running  antrea-agent       antrea-agent
``` 

ok, merging now...

**Pull request merged**
