### PR TITLE
Adding Mateusz Loskot as subproject owner

### PR DESCRIPTION
**Pull request by knabben**

### CODE REVIEW

**Review by friedrichwilken — APPROVED** [review]

**Comment by jsturtevant** [comment]
@mloskot can you take a look at https://github.com/kubernetes/community/blob/master/community-membership.md#member and follow the steps as necessary?

**Comment by mloskot** [comment]
@jsturtevant First, as I mentioned to @knabben - thank you for your trust - that although becoming an owner w/could help streamline collaboration on the SWDT CLI, I am not sure that my contributions so far carry enough weight to make me eligible for the ownership honours.

> and follow the steps as necessary?

I have read most of the documents and fulfilled all the formal requirements, apart fro requesting for a 2nd sponsor.

**Comment by mloskot** [comment]
For the records, my membership requests have been accepted:
- https://github.com/kubernetes/org/issues/4687
- https://github.com/kubernetes/org/issues/4688

Thank you everyone!

**Pull request merged**
