### PR TITLE
Replace Docker with containerd in controlplane

### LINKED ISSUE #3: modularize cri
i.e. containerd

### LINKED ISSUE #8: Add ability to create cluster with containerd

### PR DESCRIPTION
**Pull request by aravindhp**
Stop pre-pulling images and use the default registry.

Fixes #3
Fixes #8

### CODE REVIEW

**Comment by aravindhp** [comment]
/approve cancel
Just so that another approver can review and approve

**Comment by knabben** [comment]
/lgtm

@jayunit100 can you please take a look?

**Comment by knabben** [comment]
there're only 2 cases used here:

1) custom images builded 
2) settings from `variables.yml`

validating second case with < 1.23, and @aravindhp validated with 1) and 1.24
```
controlplane   Ready      control-plane,master   44s   v1.21.0   10.20.30.10   <none>        Ubuntu 20.04.3 LTS   5.4.0-81-generic   containerd://1.5.5
```

since the `tags` do not look required, approving it, if any other case (?) is not covered we open a new task for it.

/approve

**Comment by knabben** [comment]
```
vagrant ssh controlplane -c "kubectl exec -it netshoot -- curl http://whoami-windows:80/"
cni:
calico
I'm whoami-windows-59cd7b4974-tkcrr running on windows/amd64

IP: fe80::51bc:1857:3717:48db
IP: 100.244.206.70
IP: ::1
IP: 127.0.0.1
ENV: ALLUSERSPROFILE=C:\ProgramData
ENV: APPDATA=C:\Users\ContainerUser\AppData\Roaming
ENV: CommonProgramFiles=C:\Program Files\Common Files
```
```
vagrant@controlplane:~$ kubectl get nodes -o wide
NAME           STATUS   ROLES                  AGE     VERSION    INTERNAL-IP   EXTERNAL-IP   OS-IMAGE                                  KERNEL-VERSION     CONTAINER-RUNTIME
controlplane   Ready    control-plane,master   12m     v1.21.0    10.20.30.10   <none>        Ubuntu 20.04.3 LTS                        5.4.0-81-generic   containerd://1.5.5
winw1          Ready    <none>                 3m23s   v1.20.10   10.20.30.11   <none>        Windows Server 2019 Standard Evaluation   10.0.17763.737     containerd://1.5.5
```

**Pull request merged**
